name: Build Binary 

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: Install dependencies && build
        run: |
          git clone https://github.com/rileytestut/ldid.git ldid && cd ldid && sh ./make.sh
          curl -sf https://gobinaries.com/tj/node-prune | sh
          npm ci
          npm run build

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/examshell-linux
            dist/examshell-macos

